### ISSUE TITLE
how to use this js

### ISSUE THREAD

**Issue by glorysdj** [Astrocoders/auto-star-github#2]
How to use this js since we can not add it to github.com. please help. Thanks.

**Comment by guilhermedecampo** [comment]
didn't understand what you want to do. This is a chrome extension that you can install in your browser.

**Comment by glorysdj** [comment]
Thanks @guilhermedecampo, it works well as a chrome extension. We plan to make a "star me on github" hyperlink in our doc site XXX.github.io, once a user click it, a js can help to star a related repo on github.com. For now, we can only redirect to that repo when such a link is clicked. Not sure if there is any idea we can make such a link. Thanks.

**Comment by guilhermedecampo** [comment]
Hey @glorysdj 	there is no way to do this. in JS side. 
You would need to check the github API if they have a link that already start the repo for the user. like `https://github.com/Astrocoders/auto-star-github?star-it-now=true`

**Comment by glorysdj** [comment]
Thanks @guilhermedecampo. And close the issue.
